version: '3.5'
networks:
  redistest:
    name: 'redistest'
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.11.0.0/16
          ip_range: 10.11.0.0/24
          gateway: 10.11.0.1
          aux_addresses:
            redis: 10.11.0.2
services:
  # See:
  # https://hub.docker.com/_/redis
  redis:
    image: 'redis'
    container_name: 'redis'
    networks:
      - 'redistest'
    ports:
      - '6379:6379'
